name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Server Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: mise run build

  fmt:
    name: Server Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: mise run fmt-check

  lint:
    name: Server Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: mise run lint

  test-unit:
    name: Server Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: mise run test-unit

  test-integration:
    name: Server Integration Test
    runs-on: ubuntu-latest
    env:
      TEST_DATABASE_URL: mysql://test:test@127.0.0.1:3306/test
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: mise run test-integration

  dependabot-automerge:
    name: Dependabot Automerge
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    needs:
      - build
      - fmt
      - lint
      - test-unit
      - test-integration
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        uses: dependabot/fetch-metadata@v3
        id: metadata
      - uses: actions/checkout@v6
      - name: Enable automerge
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor' ||
          steps.metadata.outputs.package-ecosystem == 'github_actions'
        run: gh pr merge ${{ github.event.number }} --auto --merge
        env:
          GITHUB_TOKEN: ${{ github.token }}
